# Generated by Django 6.0.2 on 2026-09-23 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region_name', models.CharField(max_length=100)),
                ('region_code', models.CharField(blank=True, max_length=20)),
                ('demand_count', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveSmallIntegerField()),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographic_demands', to='taxonomy.normalizedrole')),
            ],
            options={
                'ordering': ['-year', 'region_name'],
                'unique_together': {('role', 'region_code', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='SectorDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.CharField(choices=[('finance', 'Finance & Banking'), ('health', 'Health'), ('government', 'Government & Public Sector'), ('telecom', 'Telecom & ICT'), ('education', 'Education'), ('retail', 'Retail & Commerce'), ('ngo', 'NGO & International Orgs'), ('other', 'Other')], max_length=50)),
                ('demand_count', models.PositiveIntegerField(default=0)),
                ('year', models.PositiveSmallIntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_demands', to='taxonomy.normalizedrole')),
            ],
            options={
                'ordering': ['-year', 'sector'],
                'unique_together': {('role', 'sector', 'year')},
            },
        ),
    ]
