# Generated by Django 6.0.8 on 2026-09-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldemand',
            name='data_basis',
            field=models.CharField(blank=True, default='', help_text="Source of this data point (e.g., 'LFS_microdata', 'back_extrapolation')", max_length=255),
        ),
        migrations.AlterField(
            model_name='macroindicator',
            name='data_source',
            field=models.CharField(blank=True, default='', help_text="e.g., 'NISR_LFS_2023', 'extrapolated'", max_length=255),
        ),
    ]
