# Generated by Django 6.0.2 on 2026-09-23 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('ict_records', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('processing_log', models.TextField(blank=True, default='')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=100)),
                ('source_job_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('location_raw', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(default='Rwanda', max_length=100)),
                ('industry_raw', models.CharField(blank=True, default='', max_length=255)),
                ('education_raw', models.CharField(blank=True, default='', max_length=255)),
                ('experience_raw', models.CharField(blank=True, default='', max_length=255)),
                ('contract_type_raw', models.CharField(blank=True, default='', max_length=100)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('is_ict', models.BooleanField(default=False)),
                ('ict_role_confidence', models.FloatField(default=0.0)),
                ('role_level', models.CharField(blank=True, default='', max_length=50)),
                ('role_normalization_confidence', models.FloatField(default=0.0)),
                ('classification_reason', models.TextField(blank=True, default='')),
                ('needs_manual_review', models.BooleanField(default=False)),
                ('manual_review_reason', models.CharField(blank=True, default='', max_length=255)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('normalized_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to='taxonomy.normalizedrole')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='uploads.dataupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
